// UI (React): HUD, panely, grafy.
export {
  EM_DASH,
  MINUS_SIGN,
  PLUS_SIGN,
  TIMES_SIGN,
  formatClock,
  formatCount,
  formatDateTime,
  formatDayAndClock,
  formatDuration,
  formatFootprint,
  formatFraction,
  formatGameTime,
  formatMoney,
  formatMoneyDelta,
  formatPercent,
  formatSpeed,
  formatXp,
  moneySign,
} from './format';
export type { GameTimeParts, TimeScale } from './format';
export { Icon, TrendIcon, iconHref, toIconName } from './icon';
export type { IconName, IconProps } from './icon';
export { SpeedControl } from './speed-control';
export type { SpeedControlProps } from './speed-control';
export { HUD_PANEL_BUTTONS, HUD_THROTTLE_MS, TopHUD, TopHUDView, resolveSpeedRequest, useSetGameSpeed } from './top-hud';
export type { TopHUDProps, TopHUDViewProps } from './top-hud';
export { BuildBar, canBuyItem, itemAction, itemDetail, itemStatus, itemTooltip, resolveItemSelection } from './build-bar';
export type {
  BuildBarCategory,
  BuildBarItem,
  BuildBarItemAction,
  BuildBarItemStatus,
  BuildBarProps,
  ItemTooltip,
} from './build-bar';
export {
  CARGO_SPLIT_DIRECTIONS,
  CARGO_SPLIT_LABELS,
  CRANE_STATE_LABELS,
  CRANE_WAITING_LABEL,
  ModuleInspector,
  RAMP_INOPERATIVE_FALLBACK,
  RAMP_INOPERATIVE_TEXTS,
  VEHICLE_STATE_INFO,
  badgeText,
  bayStates,
  berthStats,
  canSellVehicle,
  cargoSplitBarLabel,
  cargoSplitShares,
  cargoSplitText,
  cargoSplitTitle,
  cargoSplitTotal,
  craneStateLabel,
  craneStateOk,
  craneStats,
  craneTimeSplit,
  depotStats,
  emptyDepotStats,
  emptyDepotTotals,
  emptyLineText,
  emptyLineTotal,
  depotVehicleCounts,
  dockTruckLabel,
  gateStats,
  gateThroughputText,
  inspectorBadge,
  lashingProgressPct,
  lashingText,
  moduleKindIcon,
  rampInoperativeReason,
  rampInoperativeText,
  rampStats,
  rampTotals,
  repairBayStates,
  repairWaitingText,
  sellTitle,
  stagingSlots,
  storageFillPct,
  storageFree,
  storageStats,
  utilizationTone,
  visibleSplitDirections,
  vehicleCode,
  waitingAreaFree,
  waitingAreaStats,
} from './module-inspector';
export type {
  BayState,
  CargoSplitData,
  CargoSplitDirection,
  CraneStateName,
  DepotVehicleData,
  DepotVehicleState,
  EmptyDepotData,
  EmptyDepotTotals,
  EmptyLineData,
  GateData,
  InspectorBadge,
  InspectorStat,
  LashingData,
  ModuleInspectorData,
  ModuleInspectorProps,
  RampData,
  RampDockData,
  StatTone,
  VehicleStateInfo,
  WaitingAreaData,
} from './module-inspector';
export { MAX_TOASTS, TOAST_SHOW_LABEL, Toasts, visibleToasts } from './toasts';
export type { ToastData, ToastId, ToastTone, ToastsProps } from './toasts';
export {
  AT_RISK_DAYS,
  CONTRACT_TAB_LABELS,
  CUTOFF_SOON_HOURS,
  KIND_PART_NAME,
  ContractCard,
  ContractsPanel,
  SLA_OK_DAYS,
  SLA_WARN_DAYS,
  VoyageCard,
  availableEmptiesInfo,
  bookingBars,
  bookingCounters,
  contractKind,
  contractPayoutCents,
  contractSla,
  contractStatus,
  contractTab,
  contractVoyageId,
  contractsForTab,
  cutoffInfo,
  emptyState,
  exportTitle,
  offerExpiresSoon,
  offerExpiryText,
  partTitle,
  pendingArrivalsText,
  progressPercent,
  repositioningBars,
  shipText,
  tabCounts,
  transhipBars,
  transhipCounters,
  transhipLegs,
  transhipMissed,
  transhipWaitingUnits,
  voyageCardsForTab,
  voyageGroups,
  voyageKind,
  voyagePayoutCents,
  voyageTab,
  voyageTitle,
  volumeText,
} from './contracts-panel';
export type {
  BookingBar,
  BookingCounter,
  ContractBookingData,
  ContractCardData,
  ContractCardId,
  ContractCardKind,
  ContractCardProps,
  ContractCardState,
  ContractCargoCategory,
  ContractLineData,
  ContractSla,
  ContractStatus,
  ContractTone,
  ContractTranshipData,
  ContractsPanelProps,
  ContractsTab,
  ContractsTimeScale,
  CutoffInfo,
  EmptiesStock,
  TranshipLegInfo,
  TranshipMissedInfo,
  VoyageCardProps,
  VoyageGroup,
  VoyageKind,
} from './contracts-panel';
export { GameOverModal, bankruptcyText } from './game-over-modal';
export type { GameOverModalProps } from './game-over-modal';
export { FOCUSABLE_SELECTOR, ModalDialog, handleDialogKeyDown, isQuickSaveShortcut, listFocusables, trapTarget } from './modal-dialog';
export type { DialogKeyEvent, ModalDialogProps } from './modal-dialog';
export {
  AUTOSAVE_OPTIONS,
  DEFAULT_SPEED_OPTIONS,
  SOUND_NOTE,
  SettingsPanel,
  SettingsPanelView,
  commitSettings,
  settingsEqual,
  withAutosave,
  withDefaultSpeed,
} from './settings-panel';
export type { SettingsChoices, SettingsPanelProps, SettingsPanelViewProps } from './settings-panel';
export {
  EMPTY_SLOT_TEXT,
  IMPORT_ACCEPT,
  SaveLoadPanel,
  SaveLoadPanelView,
  findSlot,
  previewTimeText,
  slotName,
  slotReference,
} from './save-load-panel';
export type { SaveLoadPanelProps, SaveLoadPanelViewProps } from './save-load-panel';
export { SAVE_SLOT_IDS } from './save-types';
export type { SavePreview, SaveSlotId, SaveSlotInfo, Settings } from './save-types';
export { LINE_TOKEN_DEFAULT_FALLBACK, lineColor, lineStyle } from './line-color';
