// Typy udalostí SimEvent (readonly DTO, ARCHITECTURE §12.1).
export type {
  CargoMovedEvent,
  CommandRejectedEvent,
  CraneBlockedEvent,
  CraneBlockedReason,
  CraneCycleDoneEvent,
  DayClosedEvent,
  GameSpeedChangedEvent,
  HourClosedEvent,
  JobAssignedEvent,
  JobCancelledEvent,
  JobCreatedEvent,
  JobDoneEvent,
  ModulePlacedEvent,
  ModuleRemovedEvent,
  MoneyChangedEvent,
  MonthClosedEvent,
  NoStorageAvailableEvent,
  NoWaitingBayEvent,
  RampOperationalChangedEvent,
  RoadChangedEvent,
  ShipDepartedEvent,
  ShipDockedEvent,
  ShipSpawnedEvent,
  ShipUndockedEvent,
  SimEvent,
  SimEventOf,
  SimEventType,
  TickAdvancedEvent,
  TruckExitedEvent,
  TruckSpawnedEvent,
  TruckStateChangedEvent,
  VehicleBoughtEvent,
  VehicleSoldEvent,
  VehicleStateChangedEvent,
} from './sim-event';
