// Typy udalostí SimEvent (readonly DTO, ARCHITECTURE §12.1).
export type {
  CargoMovedEvent,
  CommandRejectedEvent,
  CraneBlockedEvent,
  CraneBlockedReason,
  CraneCycleDoneEvent,
  DayClosedEvent,
  GameSpeedChangedEvent,
  HourClosedEvent,
  ModulePlacedEvent,
  ModuleRemovedEvent,
  MoneyChangedEvent,
  MonthClosedEvent,
  RoadChangedEvent,
  ShipDepartedEvent,
  ShipDockedEvent,
  ShipSpawnedEvent,
  ShipUndockedEvent,
  SimEvent,
  SimEventOf,
  SimEventType,
  TickAdvancedEvent,
} from './sim-event';
